---
- name: Move the file to 3 remote 
  hosts: all
  become: true
  become_method: sudo
  vars:
      KEY: "{{ lookup('env', 'KEY') }}"
  tasks:
  - name: Fetch the vars from file
    shell: echo "No further things are needed..."

  - name: Create mysql user
    ansible.builtin.user:
      name: mysql
      comment: Mysql User
      group: sudo
  
  - name: Create a 2048-bit SSH key for user mysql in ~jsmith/.ssh/id_rsa
    ansible.builtin.user:
      name: mysql
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: deploy keys on all servers
    authorized_key:
      user: mysql
      key: "{{ KEY }}"
      state: present

  - name: Copy the tar.gz to the 3 remote servers
    copy:
      src: ~/pxc80-28-build-install.tar.gz
      dest: /home/mysql/

  - name: Unarchive the Tar
    unarchive:
      src: /home/mysql/pxc80-28-build-install.tar.gz
      dest: /home/mysql/
      remote_src: true


