---
- name: Move the file to 3 remote 
  hosts: all
  become: true
  become_method: sudo
  vars:
      KEY: "{{ lookup('env', 'KEY') }}"
  tasks:
  - name: Fetch the vars from file
    shell: echo "No further things are needed..."

  - name: Create mysql user
    ansible.builtin.user:
      name: mysql
      comment: Mysql User
      group: sudo
  
  - name: Create a 2048-bit SSH key for user mysql in ~jsmith/.ssh/id_rsa
    ansible.builtin.user:
      name: mysql
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: deploy keys on all servers
    authorized_key:
      user: mysql
      key: "{{ KEY }}"
      state: present

  - name: Copy the tar.gz to the 3 remote servers
    copy:
      src: ~/pxc80-28-build-install.tar.gz
      dest: /home/mysql/

  - name: Unarchive the Tar
    unarchive:
      src: /home/mysql/pxc80-28-build-install.tar.gz
      dest: /home/mysql/
      remote_src: true

  - name: Clone the PXC-XTRADB-Cluster Repository
    ansible.builtin.git:
      repo: https://github.com/percona/percona-xtradb-cluster.git
      dest: /home/mysql/percona-xtradb-cluster
      depth: 1
    tags: git

  - name: Move the Tarballs content to the Cloned Repo
    shell: mv /home/mysql/pxc80-28-build-install/install /home/mysql/percona-xtradb-cluster/install_build

  - name: Git commands to enable sub modules
    shell: cd /home/mysql/percona-xtradb-cluster && git reset --hard && git submodule foreach --recursive git reset --hard && git submodule update --init --recursive
    tags: git

  - name: Keep no Password 
    shell: "echo \"mysql ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers"
    tags: nopass

  - name: Add mysql user to sudoers group
    shell: usermod -aG sudo mysql
    tags: suoder

  - name: Ensure that the unzipped folders permission is proper
    shell: chown -R mysql:sudo /home/mysql/percona-xtradb-cluster
    tags: permissions

  - name: install XTRABACKUP
    shell: curl -O https://repo.percona.com/apt/percona-release_latest.generic_all.deb ; sudo apt install gnupg2 lsb-release ./percona-release_latest.generic_all.deb -y ; sudo apt update -y ;
    tags: pxb

  - name: Enable pxb80
    shell: sudo percona-release enable pxb-80 testing ; apt-get update -y ; apt-get install percona-xtrabackup-80 -y
    tags: pxb

  - name: Move the pxb binaries to the path
    shell: BASEDIR="/home/mysql/percona-xtradb-cluster/install_build/install" ; cp /usr/bin/xtrabackup $BASEDIR/bin/pxc_extra/pxb-8.0/bin/
    tags: pxbmove

  - name: Install Socat
    shell: sudo apt-get install socat -y
    tags: socat
