---
- name: Move the file to 3 remote 
  hosts: all
  become: true
  become_method: sudo
  vars:
      ENV_VAR_PATH: "{{ lookup('env', 'MOLECULE_ENV_FILE') }}"
  tasks:
  - name: Fetch the vars from file
    shell: echo "No further things are needed..."

  - name: Copy the tar.gz to the 3 remote servers
    copy:
      src: ~/pxc80-28-build-install.tar.gz
      dest: ~/

  - name: Unarchive the Tar
    unarchive:
      src: ~/pxc80-28-build-install.tar.gz
      dest: ~/

