---
  - name: CHECK
    hosts: localhost
    connection: local
    gather_facts: false
    tasks:
    - name: TESTING
      ansible.builtin.shell: echo "{{ lookup('env', 'INSTANCE_PRIVATE_IP') }}"
      register: HELLOS
    - name: CHECK
      debug:
        var: HELLOS
