---
- name: LogsBackup Bootstrap
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  vars:
      ENV_VAR_PATH: "{{ lookup('env', 'MOLECULE_ENV_FILE') }}"
  tasks:
    - name: Fetch the vars from file
      ansible.builtin.include_vars: "{{ ENV_VAR_PATH }}"

    - set_fact:
        man_ip={{ip_env}}
    - debug: var=man_ip

    - name: Zip the logs
      community.general.archive:
        path: /var/log
        dest: /var/log/{{test_phase}}_{{man_ip}}_logs.tar.gz

    - name: Fetch the log zip to the main node
      become: true
      ansible.builtin.fetch:
        src: /var/log/{{test_phase}}_{{man_ip}}_logs.tar.gz
        dest: "{{JENWORKSPACE}}/PXC/{{test_phase}}_{{man_ip}}/"



