---
- name: LogsBackup Bootstrap
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: debgu
      shell: echo "{{ inventory_hostname }}"

    - set_fact:
        man_ip={{ lookup('ansible.builtin.env', 'PXC1') }}
      when:  '"pxc1" in inventory_hostname'

    - set_fact:
        man_ip={{ lookup('ansible.builtin.env', 'PXC2') }}
      when:  '"pxc2" in inventory_hostname'

    - set_fact:
        man_ip={{ lookup('ansible.builtin.env', 'PXC3') }}
      when: '"pxc3" in inventory_hostname'

    - set_fact:
        jenkinsworkspace={{ lookup('ansible.builtin.env', 'JENWORKSPACE') }}
        test_phase={{ lookup('ansible.builtin.env', 'test_type') }}
      delegate_to: localhost

    - name: Zip the logs
      community.general.archive:
        path: /var/log
        dest: /var/log/{{test_phase}}_{{man_ip}}_logs.tar.gz

    - name: Fetch the log zip to the main node
      become: true
      ansible.builtin.fetch:
        src: /var/log/{{test_phase}}_{{man_ip}}_logs.tar.gz
        dest: "{{jenkinsworkspace}}/PXC/{{test_phase}}_{{man_ip}}/"



