---
- name: Create User and configure stuff
  hosts: all
  become: true
  become_method: sudo
  vars:
      KEY: "{{ lookup('env', 'KEY') }}"
  tasks:
  - name: Create mysql user
    ansible.builtin.user:
      name: mysql
      comment: Mysql User added to root group
      group: root
  
  - name: Create a 2048-bit SSH key for user mysql in ~jsmith/.ssh/id_rsa
    ansible.builtin.user:
      name: mysql
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: Create a 2048-bit SSH key for user mysql in ~jsmith/.ssh/id_rsa
    ansible.builtin.user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: deploy keys on all servers mysql server
    authorized_key:
      user: mysql
      key: "{{ KEY }}"
      state: present

  - name: deploy keys on all servers root server
    authorized_key:
      user: root
      key: "{{ KEY }}"
      state: present

  - name: Keep no Password 
    shell: "echo \"mysql ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers"
    tags: nopass

  - name: Add mysql user to sudoers group
    shell: usermod -aG root mysql
    tags: suoder

  - name: Install Socat
    shell: sudo apt-get install socat -y
    tags: socat

  - name: Fetch the vars from file
    shell: echo "No further things are needed..."
