---
# This playbook:
#   installs Percona Server 5.7 from testing repo
#   installs TokuDB, RocksDB and some other plugins
#   disables original repo
#   removes 5.7
#   enables ps-84 repo
#   installs 8.4 and repeats some tests
#   removes packages
#   NOTICE: it installs both 5.7 and 8.4 from testing repo!

- hosts: all
  become: true
  become_method: sudo
  vars: 
    major_upgrade: true
    install_mysql_shell: "{{ lookup('env', 'install_mysql_shell', default='') }}"
    gnupg_home: /root/.gnupg
    percona_key1: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    percona_key1_file: "{{ gnupg_home }}/PERCONA-PACKAGING-KEY"
  environment:
    install_mysql_shell: '{{ install_mysql_shell }}'
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

  tasks:
### start of PS 5.7 install
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for local vault setup
    include_tasks: ../tasks/setup_local_vault.yml

  - name: setup config file for keyring vault
    template: src=../scripts/ps_keyring_plugins_test/keyring_vault_test_v2.j2
              dest=/package-testing/scripts/ps_keyring_plugins_test/keyring_vault_test.cnf
              mode=0664 owner=root group=root

  - name: include tasks for enabling main repo
    include_tasks: ../tasks/enable_main_repo.yml

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: include tasks for enabling PS 8 main repo
    include_tasks: ../tasks/enable_ps8_main_repo.yml

  - name: append include for RedHat
    lineinfile:
        path: /etc/my.cnf
        line: '!includedir /etc/my.cnf.d'
    when: ansible_os_family == "RedHat"

  - name: install Percona Server 8.0 packages
    include_tasks: ../tasks/install_ps80.yml

  - name: Enable PXB 80 repo
    command: percona-release enable-only pxb-80 release

  - name: install PXB 8.0 packages
    include_tasks: ../tasks/install_pxb80.yml

  - name: install sysbench new deb packages
    include_tasks: ../tasks/install_sysbench.yml
    when:
      - lookup('env', 'install_repo') != "experimental"
      - ansible_distribution_release != "noble"

  - name: install Percona XtraBackup 8.0 packages
    include_tasks: ../tasks/install_pxb80.yml
    when: lookup('env', 'install_repo') != "experimental"

  - name: list installed packages ps80 
    include_tasks: ../tasks/list_installed_packages.yml

  - name: start mysql service with service command
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mysql service with systemctl command
    command: systemctl start mysql
    when: (ansible_distribution == "Amazon") or (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)

  - name: set root password on centos
    command: /package-testing/setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: disable selinux on centos7 for TokuDB to work
    shell: setenforce 0 || true
    when: ansible_os_family == "RedHat"

  - name: append include for RedHat
    lineinfile:
        path: /etc/my.cnf
        line: '!includedir /etc/my.cnf.d'
    when: ansible_os_family == "RedHat"

  - name: disable all percona repos
    command: percona-release disable all

  - name: get my.cnf stats
    stat: path=/etc/my.cnf
    register: mycnf

  - name: copy config file to backup
    copy:
      src: /etc/my.cnf
      dest: /etc/my.cnf.backup
      remote_src: yes
    when: mycnf.stat.exists and ansible_os_family == "RedHat"

  - name: remove Percona Server deb packages
    apt:
      name: "{{ packages }}"
      update_cache: no
      state: absent
    vars:
      packages:
      - percona-server*
    when: ansible_os_family == "Debian"

  - name: remove Percona Server rpm packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
     packages:
      - percona-server*
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - name: check /var/lib/mysql exists and not empty
    fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000

  - name: include tasks for enabling PS 84 test repo
    include_tasks: ../tasks/enable_ps84_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: install Percona Server 8.4 packages
    include_tasks: ../tasks/install_ps84.yml

  - name: Enable PXB 84 repo
    command: percona-release enable-only pxb-84-lts testing

  - name: install PXB 8.4 packages
    include_tasks: ../tasks/install_pxb84.yml

  - name: enable the Tools release repo
    command: percona-release enable tools release

  - name: install percona-mysql-shell package
    include_tasks: ../tasks/install_pshell.yml
    when: install_mysql_shell == "yes" or install_mysql_shell == ""
    
  - name: check that Percona XtraBackup version is correct
    command: /package-testing/version_check.sh pxb84
    when: lookup('env', 'install_repo') != "experimental"

  - name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

  - name: start mysql service
    service: name=mysql state=started

  - name: check that Percona Server version is correct
    command: /package-testing/version_check.sh ps84

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps84
 
#  - name: run bats tests for PAM
#    command: /usr/local/bin/bats /package-testing/scripts/ps_pam_test/ps_pam_test.bats

#  - name: keyring plugins test
#    command: /package-testing/scripts/ps_keyring_plugins_test/ps_keyring_plugins_test.sh ps84

  - name: run bats unit tests for ps-admin script
    command: /usr/local/bin/bats /package-testing/bats/ps-admin_unit.bats

  - name: run bats integration tests for ps-admin script
    command: /usr/local/bin/bats /package-testing/bats/ps-admin_integration.bats

  - name: run bats tests for mysql init scripts
    command: /usr/local/bin/bats /package-testing/bats/mysql-init-scripts.bats

  - name: remove PS 8.4 packages
    include_tasks: ../tasks/remove_ps84.yml

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped

  - stat:
      path: /var/lib/mysql
    register: p

  - name: check /var/lib/mysql exists and not empty
    fail:
      msg: "Path exists and is a directory and is not empty"
    when: p.stat.isdir is defined and p.stat.isdir and p.stat.size > 1000000
